"""Optional AI bridges for ALFADEL core.

ALFADEL remains symbolic and deterministic by default.  AI has two explicitly
separated roles:

1. candidate-constrained contextual reranking of analyses already generated by source lexical system;
2. suggestions for *unresolved* tokens, returned as unverified proposals that
   require an explicit human action before they become candidates or lexicon data.

No AI output is written to the user lexicon automatically.
"""
from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol
import json,os,shlex,subprocess,urllib.request

class AIProvider(Protocol):
    name:str
    def available(self)->bool:...
    def rerank(self,tokens:list[str],index:int,candidates:list[dict])->dict:...
    def suggest_unknown(self,tokens:list[str],index:int)->dict:...

@dataclass
class DisabledAI:
    name:str='disabled'
    def available(self):return False
    def rerank(self,tokens,index,candidates):return {"scores":{},"explanations":{}}
    def suggest_unknown(self,tokens,index):return {"suggestions":[]}

class ExternalCommandAI:
    """Vendor-neutral bridge via a user-supplied command.

    Set ``ALFADEL_AI_COMMAND``.  The command receives one JSON document on stdin.
    It can distinguish ``action=rerank`` from ``action=suggest_unknown``.
    """
    name='external-command'
    def __init__(self,command:str|None=None):self.command=command or os.getenv('ALFADEL_AI_COMMAND','')
    def available(self):return bool(self.command)
    def _call(self,payload):
        if not self.available():return {}
        p=subprocess.run(shlex.split(self.command),input=json.dumps(payload,ensure_ascii=False),text=True,
                         capture_output=True,check=True,timeout=60)
        return json.loads(p.stdout)
    def rerank(self,tokens,index,candidates):
        return _validate_rerank(self._call(_rerank_payload(tokens,index,candidates))) if self.available() else {"scores":{},"explanations":{}}
    def suggest_unknown(self,tokens,index):
        return _validate_suggestions(self._call(_unknown_payload(tokens,index))) if self.available() else {"suggestions":[]}

class JSONHTTPAI:
    """Generic JSON-over-HTTP bridge with no third-party dependency.

    Environment variables:
      ALFADEL_AI_URL            required POST endpoint
      ALFADEL_AI_BEARER_TOKEN   optional bearer token
      ALFADEL_AI_NAME           optional provider label

    The same endpoint receives both action types.  This can point to a local
    model gateway or a remote service adapter written by the user.
    """
    def __init__(self,url:str|None=None):
        self.url=url or os.getenv('ALFADEL_AI_URL','')
        self.token=os.getenv('ALFADEL_AI_BEARER_TOKEN','')
        self.name=os.getenv('ALFADEL_AI_NAME','json-http')
    def available(self):return bool(self.url)
    def _call(self,payload):
        body=json.dumps(payload,ensure_ascii=False).encode('utf-8')
        headers={'Content-Type':'application/json; charset=utf-8','Accept':'application/json'}
        if self.token: headers['Authorization']='Bearer '+self.token
        req=urllib.request.Request(self.url,data=body,headers=headers,method='POST')
        with urllib.request.urlopen(req,timeout=60) as r:
            return json.loads(r.read().decode('utf-8'))
    def rerank(self,tokens,index,candidates):
        return _validate_rerank(self._call(_rerank_payload(tokens,index,candidates))) if self.available() else {"scores":{},"explanations":{}}
    def suggest_unknown(self,tokens,index):
        return _validate_suggestions(self._call(_unknown_payload(tokens,index))) if self.available() else {"suggestions":[]}


def _window(tokens,index):
    lo=max(0,index-8); hi=min(len(tokens),index+9)
    return {"start":lo,"target":index-lo,"tokens":tokens[lo:hi]}


def _rerank_payload(tokens,index,candidates):
    return {
      "action":"rerank",
      "tokens":tokens,"target_index":index,
      "context_window":_window(tokens,index),
      "candidates":candidates,
      "instruction":"Rerank only the supplied lexical candidates in context. Do not invent a new lemma, POS, or root. Return numeric candidate scores and concise explanations."
    }


def _unknown_payload(tokens,index):
    surface=tokens[index] if 0<=index<len(tokens) else ''
    return {
      "action":"suggest_unknown",
      "tokens":tokens,"target_index":index,"surface":surface,
      "context_window":_window(tokens,index),
      "instruction":(
          "No lexical candidate was generated for this historical/Classical Arabic token. Suggest at most 5 plausible analyses. "
          "Each suggestion must contain lemma, exact_source_pos, root (empty if inapplicable), broad_pos, confidence 0..1, and a concise explanation. "
          "These are scholarly proposals only; do not claim they are verified. Prefer PROPN/loanword hypotheses when context supports them and preserve the written surface unless normalization is justified."
      )
    }


def _validate_rerank(x):
    if not isinstance(x,dict): raise ValueError('AI provider must return a JSON object')
    scores=x.get('scores',{}); ex=x.get('explanations',{})
    if not isinstance(scores,dict): raise ValueError('AI provider scores must be an object')
    return {'scores':scores,'explanations':ex if isinstance(ex,dict) else {}}


def _validate_suggestions(x):
    if not isinstance(x,dict): raise ValueError('AI provider must return a JSON object')
    rows=x.get('suggestions',[])
    if not isinstance(rows,list): raise ValueError('AI suggestions must be a list')
    out=[]
    for r in rows[:5]:
        if not isinstance(r,dict): continue
        lemma=str(r.get('lemma') or '').strip(); pos=str(r.get('exact_source_pos') or r.get('pos') or '').strip()
        if not lemma or not pos: continue
        try: conf=float(r.get('confidence',0.0))
        except: conf=0.0
        out.append({
            'lemma':lemma,'pos':pos,'root':str(r.get('root') or '').strip(),
            'broad_pos':str(r.get('broad_pos') or 'OTHER').strip().upper(),
            'confidence':max(0.0,min(1.0,conf)),
            'explanation':str(r.get('explanation') or '').strip(),
            'normalized_surface':str(r.get('normalized_surface') or '').strip(),
            'status':'unverified_ai_suggestion'
        })
    return {'suggestions':out}

# Backward-compatible aliases used by earlier tests/helpers.
def _payload(tokens,index,candidates): return _rerank_payload(tokens,index,candidates)
def _validate(x): return _validate_rerank(x)

def configured_provider():
    h=JSONHTTPAI()
    if h.available(): return h
    c=ExternalCommandAI()
    return c if c.available() else DisabledAI()
